import { ArrowLeft, Loader2, ShieldAlert, Info, Clock, AlertCircle } from "lucide-react";
import { motion } from "motion/react";
import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import { getDrugDetails } from "../services/gemini";

interface DrugDetailPageProps {
  drug: {
    name: string;
    category: string;
    description?: string;
    dosage?: string;
  };
  onBack: () => void;
  language: "EN" | "AM";
}

const Typewriter = ({ text }: { text: string }) => {
  const [displayText, setDisplayText] = useState("");
  
  useEffect(() => {
    let i = 0;
    const speed = 10;
    const charsPerTick = 15; // Very fast typing
    
    const timer = setInterval(() => {
      i += charsPerTick;
      if (i >= text.length) {
        setDisplayText(text);
        clearInterval(timer);
      } else {
        setDisplayText(text.slice(0, i));
      }
    }, speed);
    
    return () => clearInterval(timer);
  }, [text]);

  return <ReactMarkdown>{displayText}</ReactMarkdown>;
};

export default function DrugDetailPage({ drug, onBack, language }: DrugDetailPageProps) {
  const [details, setDetails] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function fetchDetails() {
      setIsLoading(true);
      const response = await getDrugDetails(drug.name, language);
      setDetails(response);
      setIsLoading(false);
    }
    fetchDetails();
  }, [drug.name, language]);

  const t = {
    EN: {
      loading: "Retrieving medical data...",
      disclaimer: "Medical Disclaimer:",
      disclaimerText: "This information is generated by AI for educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.",
    },
    AM: {
      loading: "የሕክምና መረጃ በማምጣት ላይ...",
      disclaimer: "የሕክምና ማስጠንቀቂያ፡",
      disclaimerText: "ይህ መረጃ ለትምህርት ዓላማ ብቻ በAI የተዘጋጀ ነው። ለሙያዊ የሕክምና ምክር፣ ምርመራ ወይም ሕክምና ምትክ አይደለም። ስለ የሕክምና ሁኔታ ማንኛውም ጥያቄ ካለዎት ሁል ጊዜ የሐኪምዎን ወይም ሌላ ብቁ የጤና አቅራቢን ምክር ይጠይቁ።",
    }
  }[language];

  return (
    <div className="flex flex-col h-full bg-[#0A0A0A] text-white font-sans overflow-hidden">
      {/* Header */}
      <nav className="sticky top-0 z-50 bg-[#0A0A0A]/80 backdrop-blur-md border-b border-white/5 px-4 py-4 flex items-center gap-4">
        <button 
          onClick={onBack}
          className="p-2 hover:bg-white/5 rounded-full transition-colors text-white/70"
        >
          <ArrowLeft size={20} />
        </button>
        <div>
          <h1 className="font-bold text-lg tracking-tight text-white">{drug.name}</h1>
          <p className="text-[10px] text-blue-400 font-bold uppercase tracking-[0.2em]">{drug.category}</p>
        </div>
      </nav>

      <div className="flex-1 overflow-y-auto pb-32">
        <div className="p-6 space-y-10">
          {/* AI Detailed Content */}
          <div className="max-w-2xl mx-auto">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-32 space-y-4">
              <Loader2 size={32} className="text-blue-500 animate-spin" />
              <p className="text-white/40 text-sm font-medium tracking-wide">{t.loading}</p>
            </div>
          ) : (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="markdown-body prose prose-invert max-w-none 
                prose-p:text-white/90 prose-p:leading-relaxed prose-p:text-lg prose-p:mb-8
                prose-headings:text-white prose-headings:font-bold prose-headings:tracking-tight
                prose-h3:text-xl prose-h3:mt-10 prose-h3:mb-4 prose-h3:text-blue-400
                prose-li:text-white/90 prose-li:text-lg prose-li:mb-4
                prose-strong:text-white prose-strong:font-bold"
            >
              <Typewriter text={details} />
            </motion.div>
          )}
        </div>

        {/* Disclaimer */}
        {!isLoading && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="max-w-2xl mx-auto bg-white/5 border border-white/10 p-6 rounded-[24px] flex gap-4"
          >
            <Info className="text-blue-400 flex-shrink-0" size={20} />
            <p className="text-[11px] text-white/40 leading-relaxed">
              <strong className="text-white/60">{t.disclaimer}</strong> {t.disclaimerText}
            </p>
          </motion.div>
        )}
      </div>
    </div>
    </div>
  );
}
